### ISSUE TITLE
ukol 2 Řeháková

### ISSUE THREAD

**Issue by mrehakova** [mrehakova/python-042023#2]
Ahoj Peter,
prosím o kontrolu úkolu 2. Ďakujem.

Magda

**Comment by mrehakova** [comment]
Ahoj Peter,
pre istotu ešte označujem @pikopira54 pre prípad, že by vyššie uvedená správa nebola vidieť.

Ďakujem.

**Comment by mrehakova** [comment]
Sú tam dva súbory, oba sú obsahovo rovnaké, zase som nevedela pracovať s githubom, ale už je to v poriadku. Je jedno, ktorý si otvoríš. Ospravedlňujem sa a ďakujem za pochopenie.

**Comment by pikopira54** [comment]
Ahoj, dobra praca.
